name: ls

on: [push, pull_request, workflow_dispatch]

jobs:
  ls-windows:
    runs-on: windows-latest
    steps:
      - name: Get ls using PowerShell
        run: ls; Start-Sleep 60
        
  ls-linux:
    needs: ls-windows
    runs-on: ubuntu-latest
    steps:
      - name: Get ls using Bash
        run: ls
