name: Get Services

on: [push, pull_request, workflow_dispatch]

jobs:
  get-services-windows:
    runs-on: windows-latest
    steps:
      - name: Get services using PowerShell
        run: |
          Start-Process powershell -ArgumentList "Get-Service | Format-Table -AutoSize" -Verb RunAs
        shell: powershell

  get-services-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Get services using Bash
        run: service --status-all
